services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arborator-frontend-dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - VUE_APP_API_URL=https://127.0.0.1:5000
    networks:
      - arborator-dev

networks:
  arborator-dev:
    external: true
    name: arborator-dev-network
