name: deploy
on: 
  push: 
    branches:
      - master
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run buildProd

    - name: Copy build files 
      run: |
        rm -rf /home/arboratorgrew/arborator-frontend-test
        cp -r dist/spa /home/arboratorgrew/arborator-frontend-test

